site_name: FEniCS-Reinforcement
site_description: Steel rebar reinforcement in FEniCSx models
site_author: BAMreasearch

repo_url: https://github.com/BAMresearch/fenics-reinforcement

theme:
  name: "material"
plugins:
  - mkdocstrings
nav:
  - Start: index.md
  - Demos:
    - 3-point bending: demos/3-point-bending.md
  - API:
    - Mesh: API/mesh_generation.md
    - Rebar: API/rebar.md
