site_name: My Docs

theme:
  name: "material"
plugins:
  - mkdocstrings
nav:
  - Start: index.md
  - Demos:
    - 3-point bending: demos/3-point-bending.md
  - API:
    - Mesh: API/mesh_generation.md
    - Rebar: API/rebar.md