name: Docs

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  buid_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: reinforcement_docs
            use-mamba: true
            python-version: 3.9

      - name: Update environment
        run: mamba install mkdocs mkdocstrings mkdocstrings-python mkdocs-material
      
      - name: Make docs
        run: mkdocs gh-deploy --force


